blog/urls.py
from django.conf.urls import url
from blog.views import blog_page

urlpatterns = [
  url(r'^(?P<slug>[-\w]+)/?$', blog_page, name='post-view'),
]

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings
import datetime, markdown, re
from django.template import loader, Context

from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import SimpleUploadedFile, UploadedFile
import os
import html
# Create your models here.

def attributes_to_dict(attributes):
    d = {}
    for pair in attributes.split(","):
        kv = pair.split(":")
        if len(kv) == 1:
            d[kv[0].strip()] = True
        else:
            key = kv[0].strip()
            val = kv[1].strip()
            
            if(val.lower() == "true"):
                d[key] = True
            elif(val.lower() == "false"):
                d[key] = False
            elif(val.lower() == "none"):
                d[key] = None
            else:
                d[key] = val
    return d

class FilterProcessor:
    summary_start = 0
    summary_end = 1000
    incode = False
    code_language = None
    code_start = 0
    code_linenumbers = False
    refs_start = 0
    
    def __init__(self):
        self.figure_template = loader.get_template('blog/figure.html')
        self.gallery_template = loader.get_template('blog/gallery.html')
        self.group_template = loader.get_template('blog/group.html')
        self.tags = {
            'figure': self.tag_figure, 
            'summary': self.tag_summary,
            'code': self.tag_code,
            'gallery': self.tag_gallery,
            'refs': self.tag_refs,
            'group': self.post_group,
            }
        
    def run(self, md, slug):
        self.source = md
        self.slug = slug
        filter_re = re.compile(r'(?<!\\)\{(?P<tag_name>[a-zA-Z0-9\-_]+)\|(?P<attributes>.*?)\}')
        
        tokens = []
        pos = 0
        for m in filter_re.finditer(self.source):
            tokens.append(("literal", self.source[pos:m.start()]))
            tokens.append(("tag", m.group('tag_name'), m.group('attributes'), m.group(0)))
            pos = m.end()
            
        if(pos < len(self.source)):
            tokens.append(("literal", self.source[pos:]))
            
        self.output = ""
        for token in tokens:
            if(token[0] == "literal"):
                self.output += token[1]
            else:
                if self.incode and token[1] != "code":
                    self.output += token[3]
                else:
                    kw = attributes_to_dict(token[2])
                    self.tags[token[1]](**kw)
                
    
    def tag_figure(self, name=None, ref=None, thumbnail=True, title=True, caption=True, border=True):
        if name:
            """ This is a request to insert a named figure """
            fig = Figure.objects.get(label=name)
            self.output += self.figure_template.render({"figure": fig,
                                                        "thumbnail": thumbnail,
                                                        "title": title,
                                                        "caption": caption,
                                                        "border": border})
        else:
            """ This is a request to link to a named figure within this page """
            pass
    
    def tag_gallery(self, name):
        gallery = Gallery.objects.get(label=name)
        figures = Figure.objects.filter(gallery=gallery)
        
        self.output += self.gallery_template.render({"figures": figures})
        
    def tag_summary(self, start=False, end=False):
        if start:
            self.summary_start = len(self.output)
        if end:
            self.summary_end = len(self.output)

    def tag_code(self, begin=False, language=None, linenumbers=False, end=False):
        if end:
            """ Found the end of the code tag, process the output since code start """
            code_content = self.output[self.code_start:]
            
            # do syntax highlighting, linenumbers etc here
            
            self.output = (self.output[:self.code_start] + "<div class='code'><pre><code>"
                + code_content + "</code></pre></div>")
            self.incode = False
        else:
            """ Code start, store a global flag to treat the content as literal """
            self.incode = True
            self.code_language = language
            self.code_linenumbers = linenumbers
            self.code_start = len(self.output)
            
    def tag_refs(self, begin):
        self.refs_start = len(self.output)
        
    def get_rendered(self):
        return markdown.markdown(self.output, output_format="html5", extensions=["tables"])
        
    def get_summary(self):
        if self.refs_start > 0:
            summary = self.output[self.summary_start:self.summary_end] + self.output[self.refs_start:]
        else:
            summary = self.output[self.summary_start:self.summary_end]
        return markdown.markdown(summary, output_format="html5", extensions=["tables"])
        
    def post_group(self, name, two_column=False):
        postgroup = PostGroup.objects.get(slug=name)
        posts = PostGroupItem.objects.filter(group=postgroup)
        externals = ExternalGroupItem.objects.filter(group=postgroup)
        
        self.output += self.group_template.render({"slug": self.slug,
                                                   "group": postgroup,
                                                   "posts": posts,
                                                   "externals": externals,
                                                   "two_column": two_column})
        
class Post(models.Model):
  title = models.CharField(max_length=1000)
  slug = models.SlugField(blank=True, unique=True)
  last_modified = models.DateTimeField(blank=True)
  source = models.TextField()
  rendered = models.TextField(blank=True)
  summary = models.TextField(blank=True)
  published = models.BooleanField(default=False)
  special = models.BooleanField(default=False)
  reviewed = models.BooleanField(default=False)
  section = models.ForeignKey('Section', on_delete=models.PROTECT)
  
  def __str__(self):
    return self.title
  
  def get_tags(self):
      return Tag.objects.filter(pk__in=PostTag.objects.filter(post=self).values_list('tag', flat=True))
      
  def get_attachments(self):
      return Attachment.objects.filter(post=self)
      
  def get_comments(self):
      return Comment.objects.filter(post=self, parent__isnull=True, approved=True).order_by('posted')
      
  def save(self, *args, **kwargs):
    if not self.id:
      self.slug = slugify(self.title[:Post._meta.get_field('slug').max_length])
      
    if not self.last_modified:
      self.last_modified = datetime.datetime.now()
      
    pr = FilterProcessor()
    pr.run(self.source, self.slug)
  
    self.rendered = pr.get_rendered()
    self.summary = pr.get_summary()
    super(Post, self).save(*args, **kwargs)

class Figure(models.Model):
  img = models.ImageField(upload_to="images")
  thumbnail = models.ImageField(upload_to="images", blank=True, null=True)
  title = models.CharField(max_length=50)
  caption = models.TextField(blank=True, null=True)
  label = models.SlugField(unique=True)
  gallery = models.ForeignKey('Gallery', on_delete=models.SET_NULL, blank=True, null=True)
  created = models.DateTimeField(auto_now_add=True)
  modified = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.label
    
  def preview_tag(self):
      return u'<img src="%s" alt="%s"/>' % (self.thumbnail.url, self.caption)
  preview_tag.short_description = "Preview"
  preview_tag.allow_tags = True
      
  def make_thumbnail(self):
    if not self.img:
      return
    
    if (not isinstance(self.img.file, UploadedFile)) and (self.thumbnail):
      return
      
    THUMBNAIL_SIZE = (600,400)
    
    if isinstance(self.img.file, UploadedFile):
      if self.img.file.content_type == 'image/jpeg':
        pil_type = 'jpeg'
        file_extension = 'jpg'
        content_type = 'image/jpeg'
      elif self.img.file.content_type == 'image/png':
        pil_type = 'png'
        file_extension = 'png'
        content_type = 'image/png'
    else:
      if os.path.splitext(self.img.name)[1].strip(".").lower() == "jpg":
        pil_type = 'jpeg'
        file_extension = 'jpg'
        content_type = 'image/jpeg'
      else:
        pil_type = 'png'
        file_extension = 'png'
        content_type = 'image/png'
        
    image = Image.open(BytesIO(self.img.read()))
        
    image.thumbnail(THUMBNAIL_SIZE, Image.LANCZOS)
    
    temp = BytesIO()
    image.save(temp, pil_type)
    temp.seek(0)
    
    fd = SimpleUploadedFile(os.path.split(self.img.name)[-1], 
                            temp.read(), content_type=content_type)
    
    thumbnail_name = "images/%s.preview.%s" % (os.path.splitext(fd.name)[0], file_extension)

    if(os.path.exists(os.path.join(settings.MEDIA_ROOT, thumbnail_name))):
      os.remove(os.path.join(settings.MEDIA_ROOT, thumbnail_name))
    self.thumbnail.save(thumbnail_name, fd, save=False)
    
  def scale_image(self):
    if not isinstance(self.img.file, UploadedFile):
      return
    
    if self.img.file.content_type == 'image/jpeg':
      pil_type = 'jpeg'
      file_extension = '.jpg'
    elif self.img.file.content_type == 'image/png':
      pil_type = 'png'
      file_extension = '.png'
    
    if hasattr(self.img.file, 'temporary_file_path'):
      image = Image.open(self.img.file.temporary_file_path())
    else:
      # thumbnail will have already read the file from memory
      self.img.file.seek(0)
      image = Image.open(BytesIO(self.img.file.read()))
    
    image.thumbnail((1600, 1600), Image.LANCZOS)
    
    temp = BytesIO()
    image.save(temp, pil_type)
    temp.seek(0)
    
    fd = SimpleUploadedFile(os.path.splitext(self.img.name)[0] + file_extension, 
                            temp.read(),

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.template import loader
from django.shortcuts import get_object_or_404
from blog.models import Post, LegacyNode, ForeignNode, Attachment, Comment, Section, PostTag, Tag, Gallery
from math import ceil
from django.contrib.sites.shortcuts import get_current_site
# Create your views here.

def template_name(request):
  return "base_" + get_current_site(request).domain + ".html"

def pagination(num_posts, limit, url_base):
    pages = int(ceil(num_posts / 10.0))
  
    if(limit > 0):
        prev_page = limit
    else:
        prev_page = False
    if(limit < pages-1):
        next_page = limit + 2
    else:
        next_page = False

    t = loader.get_template('blog/paginator.html')
    c = {
        'num_pages': pages,
        'pages': range(1, pages+1),
        'page': limit + 1,
        'next': next_page,
        'prev': prev_page,
        'page0': url_base
    }
    return t.render(c)

def home(request, offset="1"):
  current_site = get_current_site(request)
  limit = int(offset) - 1
  posts = Post.objects.filter(published=True, special=False).order_by('-last_modified')[limit*10:(limit+1)*10]
  
  num_posts = Post.objects.filter(published=True, special=False).count()
  
  paginator = pagination(num_posts, limit, '/')
  
  t = loader.get_template('blog/index.html')
  c = {
    'base_template': template_name(request),
    'posts': posts, 'area': 'Home', 
    'title': current_site.domain + ' : Home', 
    'paginator': paginator
  }
 
  return HttpResponse(t.render(c, request))
  
def section(request, section, offset="1"):
  current_site = get_current_site(request)
  limit = int(offset) - 1
  sec = get_object_or_404(Section, url=section)
  posts = Post.objects.filter(published=True, special=False, section=sec).order_by('-last_modified')[limit*10:(limit+1)*10]
  
  num_posts = Post.objects.filter(published=True, special=False, section=sec).count()
  paginator = pagination(num_posts, limit, '/section/' + section + '/') 
  
  t = loader.get_template('blog/index.html')
  c = {
    'base_template': template_name(request),
    'posts': posts, 'area': sec.title, 
    'title': current_site.domain + ' : ' + sec.title,
    'paginator': paginator
  }
  
  return HttpResponse(t.render(c, request))

def tagged_posts(request, tag_name, offset="1"):
  current_site = get_current_site(request)
  limit = int(offset) - 1
  tag = get_object_or_404(Tag, slug=tag_name)
  post_tags = PostTag.objects.filter(tag=tag).values_list('post', flat=True)
  posts = Post.objects.filter(published=True, special=False, pk__in=post_tags).order_by('-last_modified')[limit*10:(limit+1)*10]
  
  num_posts = Post.objects.filter(published=True, special=False, pk__in=post_tags).count()
  paginator = pagination(num_posts, limit, '/tag/' + tag_name + '/')
  
  t = loader.get_template('blog/index.html')
  c = {
    'base_template': template_name(request),
    'posts': posts,
    'area': tag.text, 
    'title': current_site.domain + ' : ' + tag.text,
    'paginator': paginator
  }
  
  return HttpResponse(t.render(c, request))

def tree_comments(comment, depth):
    comm_list = []
    comm_list.append((comment, depth))
    for comm in comment.get_children():
        comm_list.extend(tree_comments(comm, depth+1))
    return comm_list
        
def blog_page(request, slug):
  current_site = get_current_site(request)
  post = get_object_or_404(Post, slug=slug, published=True, special=False)
  
  att = Attachment.objects.filter(post=post).all()
  
  comments = post.get_comments()
  dl = None
  if(comments):
    recursed_comments = []
    for comment in comments:
        recursed_comments.extend(tree_comments(comment, 0))
    
    dl = []
    for i in range(len(recursed_comments)-1):
        depths_to_close = range(recursed_comments[i][1] - recursed_comments[i+1][1] + 1)
        dl.append((recursed_comments[i][0], depths_to_close))
    
    dl.append((recursed_comments[-1][0], range(recursed_comments[-1][1]+1)))
  
  t = loader.get_template('blog/page.html')
  c = {
    'base_template': template_name(request),
    'site': current_site,
    'post': post, 
    'atts': att, 
    'comments': dl
  }
  
  return HttpResponse(t.render(c, request))

def special_page(request, slug):
    current_site = get_current_site(request)
    doc = get_object_or_404(Post, slug=slug, published=True, special=True)
    
    att = Attachment.objects.filter(post=doc)
    
    comments = Comment.objects.filter(post=doc, approved=True)
    
    tags = PostTag.objects.filter(post=doc)
    
    t = loader.get_template('blog/page.html')
    c = {
        'base_template': template_name(request),
        'site': current_site,
        'post': doc, 
        'atts': att, 
        'comments': None
    }
    
    return HttpResponse(t.render(c, request))

def legacy_node(request, nid):
  try:
    node = LegacyNode.objects.get(node=nid)
  except LegacyNode.DoesNotExist:
    node = get_object_or_404(ForeignNode, node=nid)
    return HttpResponsePermanentRedirect("http://hairymnstr.com/node/%d" % (node.node))
  return HttpResponsePermanentRedirect("/blog/" + node.post.slug)
  
def gallery_index(request):
    current_site = get_current_site(request)
    galleries = Gallery.objects.filter(hidden=False).order_by('-gallery_date')
    
    t = loader.get_template('blog/gallery_index.html')
    c = {
        'base_template': template_name(request),
        'site': current_site,
        'galleries': galleries
    }
    
    return HttpResponse(t.render(c, request))

def gallery(request, slug):
    current_site = get_current_site(request)
    gallery = get_object_or_404(Gallery, label=slug)
    
    t = loader.get_template('blog/gallery_live.html')
    c = {
        'base_template': template_name(request),
        'site': current_site,
        'gallery': gallery
    }
    
    return HttpResponse(t.render(c, request))

blog/templates/blog/figure.html
<div style="width: 100%">
  <div class="nd-dark-grey" style="margin: auto; max-width:{% if thumbnail %}{{figure.thumbnail.width}}px">
  <a href="{{figure.img.url}}">
    <img src="{{figure.thumbnail.url}}" title="{{figure.title}}" alt="{{figure.caption}}"/>
  </a>{% else %}{{figure.img.width}}px">
  <img src="{{figure.img.url}}" title="{{figure.title}}" alt="{{figure.caption}}"/>
  {% endif %}<div class="w3-container"><p>{% if title %}<strong>{{figure.title}}:</strong> {% endif %}
  {% if caption %}{{figure.caption}}{% endif %}</p></div></div>
</div>

blog/templates/blog/gallery.html
<div class="gallery">{% for figure in figures %}
  <div class="gallery-responsive">
  <div class="gallery-frame">
  <div class="gallery-image">
  <div class="gallery-image-inner">
  <a href="{{figure.img.url}}">
    <span class="helper"></span><img src="{{figure.thumbnail.url}}" title="{{figure.title}}" alt="{{figure.caption}}"/>
  </a>
  </div>
  </div>
  <p class="w3-container"><strong>{{figure.title}}:</strong> {{figure.caption|safe}}</p>
  </div>
  </div>{% if forloop.last %}<div class="gallery-clearfix"></div>{% elif forloop.counter|divisibleby:2 or forloop.counter|divisibleby:3 %}<div class="{% if forloop.counter|divisibleby:2 %}gallery-clearfix2 {% endif %}{% if forloop.counter|divisibleby:3 %}gallery-clearfix3{% endif %}"></div>{% endif %}{% endfor %}
</div>

blog/templates/blog/gallery_index.html
{% extends base_template %}
{% block title %}{{ site.domain }} : Galleries{% endblock %}
{% block area %}Galleries{% endblock %}
{% block content %}
    <div class='gallery'>
    {% for gallery in galleries %}
        <div class='gallery-responsive'>
			<div class='gallery-frame'>
				<div class='gallery-image'>
					<div class='gallery-image-inner'>
                		<a href="/gallery/{{gallery.label}}/">
                    		<span class="helper"></span><img src="{{gallery.cover_image.thumbnail.url}}" title="{{gallery.title}}" alt="{{gallery.cover_image.caption}}"/>
                		</a>
            		</div>
				</div>
				<p class='w3-container'><strong>{{gallery.title}}</strong> {{gallery.description|safe}}<br/>
            	<span class='pubdate'>{{gallery.gallery_date|date:"d M Y"}}</span></p>
			</div>
        </div>{% if forloop.last %}<div class='gallery-clearfix'></div>{% elif forloop.counter|divisibleby:2 or forloop.counter|divisibleby:3 %}<div class='{% if forloop.counter|divisibleby:2 %}gallery-clearfix2 {% endif %}{% if forloop.counter|divisibleby:3 %}gallery-clearfix3{% endif %}'></div>{% endif %}
    {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/gallery_live.html
{% extends base_template %}
{% block title %}{{ site.domain }} : {{ gallery.title }}{% endblock %}
{% block area %}{{ gallery.title }}{% endblock %}
{% block content %}
    <div class='gallery'>
    {% for figure in gallery.figure_set.all %}
        <div class='gallery-responsive'>
			<div class='gallery-frame'>
				<div class='gallery-image'>
					<div class='gallery-image-inner'>
                		<a href="{{figure.img.url}}">
                    		<span class="helper"></span><img src="{{figure.thumbnail.url}}" title="{{figure.title}}" alt="{{figure.cover_image.caption}}"/>
                		</a>
            		</div>
				</div>
            	<p class='w3-container'>{{figure.caption|safe}}</p>
			</div>
        </div>{% if forloop.last %}<div class='gallery-clearfix'></div>{% elif forloop.counter|divisibleby:2 or forloop.counter|divisibleby:3 %}<div class='{% if forloop.counter|divisibleby:2 %}gallery-clearfix2 {% endif %}{% if forloop.counter|divisibleby:3 %}gallery-clearfix3{% endif %}'></div>{% endif %}
    {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/group.html
<div class='related_posts'>
<h3>This post is part of the {{group.group_name}} series</h3>
{% if two_column and posts and externals %}
<div class='left_column'>
<h4>Related Posts</h4>
{% for item in posts %}
<a {% if item.post.slug == slug %}class='active'{% endif %} href='{% url blog.views.blog_page item.post.slug %}'>{{ item.post.title }}</a><br/>
{% endfor %}
</div>
<div class='right_column'>
<h4>External Links</h4>
{% for item in externals %}
<a href='{{ item.url }}'>{{ item.description }}</a><br/>
{% endfor %}
</div>
{% else %}
{% if posts %}
<h4>Related Posts</h4>
{% for item in posts %}
<a {% if item.post.slug == slug %}class='active'{% endif %} href='{% url blog.views.blog_page item.post.slug %}'>{{ item.post.title }}</a><br/>
{% endfor %}
{% endif %}
{% if externals %}
<hr/>
<h4>External Links</h4>
{% for item in externals %}
<a href='{{ item.url }}'>{{ item.description }}</a><br/>
{% endfor %}
{% endif %}
{% endif %}
</div>

blog/templates/blog/index.html
{% extends base_template %}
{% block title %}{{ title }}{% endblock %}
{% block area %}{{ area }}{% endblock %}
{% block content %}
    {{ paginator }}

    {% for post in posts %}
    <div class='post-summary'>
        <h2><a href='/blog/{{ post.slug }}'>{{post.title}}</a></h2>
        <p class='pubdate'>Last updated: {{post.last_modified|date:"d M Y - H:i"}}</p>
        {{ post.summary|safe }}
        <dl class='tags'>
            <dt>Section:</dt>
            <dd><a href='/section/{{ post.section.url }}'>{{ post.section.title }}</a></dd>
        </dl>
        <dl class='tags'>
            <dt>Tags:</dt>
            {% for tag in post.get_tags %}
                <dd><a href='/tag/{{tag.slug}}'>{{ tag.text }}</a>{% if not forloop.last %},{% endif %}</dd>
            {% empty %}
                <dd>&nbsp;</dd>
            {% endfor %}
        </dl>
    </div>
    {% endfor %}

    {{ paginator }} 
{% endblock %}

blog/templates/blog/link_status.html
{% extends 'admin/base_site.html' %}
{% block content %}
    <table>
        {% for page in pages %}
        <tr><th colspan='3'>{{page.title}}</th></tr>
        {% for link in page.links %}
        <tr {{link.style|safe}}><td>{{link.url}}</td><td>{{link.code}}</td><td>{{link.extra}}</td></tr>
        {% endfor %}
        {% for image in page.images %}
        <tr {{image.style|safe}}><td>{{image.url}}</td><td>{{image.code}}</td><td>{{image.extra}}</td></tr>
        {% endfor %}
        {% endfor %}
    </table>
{% endblock %}

blog/templates/blog/page.html
{% extends base_template %}
{% block title %}{{site.domain}} : {{ post.title }}{% endblock %}
{% block area %}{{ post.section.title }}{% endblock %}
{% block content %}
    <header>
      <h1>{{post.title}}</h1>
      <p class='pubdate'>Last updated: {{ post.last_modified }}</p>
    </header>
    {{ post.rendered|safe }}
    {% if post.get_attachments %}
    <table>
      <tr><th>Attachment</th><th>Last Update</th><th>Size</th></tr>
    {% for att in post.get_attachments %}
      <tr><td><a href='{{att.file.url}}'>{{att.description}}</a></td><td>{{att.updated}}</td><td>{{att.size|filesizeformat}}</td></tr>
    {% endfor %}
    </table>
    {% endif %}
    <dl class='tags'>
        <dt>Section:</dt>
        <dd><a href='/section/{{post.section.url}}'>{{post.section.title}}</a></dd>
    </dl>
    <dl class='tags'>
        <dt>Tags:</dt>
        {% for tag in post.get_tags %}
        <dd><a href='/tag/{{tag.slug}}'>{{tag.text}}</a>{% if not forloop.last %},{% endif %}</dd>
        {% empty %}
        <dd>&nbsp;</dd>
        {% endfor %}
    </dl>
    <h3>Comments</h3>
    {% for comment, closings in comments %}
    <div class='comment'>
        <h4>{{ comment.title }}</h4>
        <p class='pubdate'>{{comment.posted|date:"d M Y - H:i"}} {{comment.posted_by}}</p>
        {{comment.content_cleaned|safe}}
    {% for c in closings %}
    </div>
    {% endfor %}
    {% endfor %}
    <p>Posting comments is not currently possible.  If you want to discuss this article
    you can reach me on <a href='https://twitter.com/hairymnstr'>twitter</a> or via
    <a href='mailto:nathan@nathandumont.com'>email</a>.</p>
    <hr class='clear'/>
{% endblock %}

blog/templates/blog/paginator.html
    <div class='nd-pagination'>
        <ul class='w3-pagination'>
            <li><a href='{{ page0 }}'>&laquo;</a></li>
            {% for p in pages %}
            <li><a{% if page == p %} class='nd-light-blue'{% endif %} href='{{ page0 }}page/{{p}}'>{{p}}</a></li>
            {% endfor %}
            <li><a href='{{ page0 }}page/{{ num_pages }}'>&raquo;</a></li>
        </ul>
    </div>

blog/templates/blog/verify.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static admin_modify %}
{% load url from future %}
{% load admin_urls %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ app_label|capfirst|escape }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; <a href='{% url 'admin:blog_post_change' post.id %}'>{{ original|truncatewords:"18" }}</a>
&rsaquo; Validation
</div>
{% endblock %}
{% endif %}

{% block content %}
    <pre>
    {{errors}}
    </pre>
{% endblock %}